# Site settings
title: "Tristan Turakiewicz
Data Science | BI | Engineering"
email: "turakiewicz.tristan06@email.com"  # Mets ton email (optionnel)
description: >-
  Enthusiastic about leveraging data through predictive modeling, advanced data analysis, business intelligence dashboards, and data engineering to drive impactful business solutions and continuous improvement.
github_username: turakiewicztristan
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Paris  # ou ta timezone

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Tristan Turakiewicz"
  avatar: "/assets/images/cv_photo.jpg"   # Tu peux changer ou enlever si tu veux
  bio: "Data enthusiast skilled in analytics, statistics, and machine learning, with hands-on experience in Python, SQL, DBT, Scikit-learn, etc.
Comfortable turning raw data into insights to support data-driven decisions.
Open to roles in data analysis, BI, data science, or data engineering."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tristanturakiewicz"
    - label: "French Resume"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/images/cv_tristan_turakiewicz.pdf"
    - label: "English Resume"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/images/cv_tristan_turakiewicz_eng.pdf"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tristanturakiewicz"
    - label: "My Resume"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/images/cv_tristan_turakiewicz.pdf"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
