# Site settings
title: "Tristan Turakiewicz Data Professional | Data Science, BI & Engineering"
email: "turakiewicz.tristan06@email.com"  # Mets ton email (optionnel)
description: >-
  Passionate about predictive modeling, data analysis, BI dashboards, and data engineering.
github_username: turakiewicztristan
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Paris  # ou ta timezone

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Tristan turakiewicz"
  avatar: "/assets/images/cv_photo.jpg"   # Tu peux changer ou enlever si tu veux
  bio: "Data scientist expert in predictive modeling, BI, and data pipelines."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "www.linkedin.com/in/tristanturakiewicz"
    - label: "Mon CV"
    icon: "fas fa-fw fa-file-pdf"
    url: "/assets/images/cv_tristan_turakiewicz.pdf"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "www.linkedin.com/in/tristanturakiewicz"
    - label: "Mon CV"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/images/cv_tristan_turakiewicz.pdf"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
